name: parse_facade
description: parse_facade interfaces with Parse's javascript SDK for working with parse-server
version: 0.0.2
author: Kulshekhar Kabra <kulshekhar+dart@gmail.com>
homepage: https://github.com/kulshekhar/parse-facade

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies: 
  js: '^0.6.1'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  xhr_interceptor_facade: '^0.0.1'
